### ISSUE TITLE
[question] How do you change the colours?

### ISSUE THREAD

**Issue by 42willow** [catppuccin/gnome-terminal#10]
![image](https://github.com/catppuccin/gnome-terminal/assets/70784752/d76e8e69-974c-4493-bd8a-bb176467f2a8)

How do you change the colours as seen in this screen shot (i.e the pink highlight on username)? Is this achieved with oh my bash themes? I'm new to the gnome terminal.

**Comment by nekowinston** [comment]
> Is this achieved with oh my bash themes?

Yes. The terminal theme only sets the colors 0-15 in your terminal, you need to set your shell prompt separately (bashrc/zshrc/fish config etc.).

**Comment by 42willow** [comment]
Ok thanks. Just started using Linux as a daily driver (from Windows) and I'm loving it.
