### ISSUE TITLE
Catppuccin Latte has bright text colors

### ISSUE THREAD

**Issue by mainrs** [catppuccin/gnome-terminal#12]
![image](https://github.com/catppuccin/gnome-terminal/assets/5113257/82543502-0b53-4809-8a6a-ebad552fec42)

I installed the theme on a fresh Manjaro + GNOME machine. The text seems to use the dark theme Frappe color scheme. The colors look kind of pastelle.

The contrast is super low and it's hard to read any text in the terminal. Any idea what is going on?

If you need some diagnostics, let me know.

**Comment by backwardspy** [comment]
hi @mainrs, apologies for the lack of movement on this issue. did you manage to fix it, or did you stop using the theme?

my first guess is that your shell (bash/zsh/etc) theme was set to frappé resulting in the wrong syntax colours being used.

if this is no longer an issue, let me know and i'll close it!

**Comment by mainrs** [comment]
No, never managed to fix it. I also thought that the shell theme might be the wrong one. I switched over to alacritty and haven't had any issues there.

**Comment by backwardspy** [comment]
thanks for the update! :)
