### ISSUE TITLE
Which tool used for screenshots?

### ISSUE THREAD

**Issue by Zaphoood** [catppuccin/gnome-terminal#13]
What's the name of the neofetch-like tool used to create the sample output in the screenshots? The cat ascii art looks really cute.

Thanks in advance and sorry if this is the wrong place to ask this question.

**Comment by nekowinston** [comment]
It's based off [pfetch](https://github.com/dylanaraps/pfetch), the script is [here](https://gist.github.com/nekowinston/f81c759bf3be78c30fa15c7f5f2a6e25).

If you want it to show real system data, use: https://github.com/andreasgrafen/pfetch-with-kitties

**Comment by Zaphoood** [comment]
Thanks!
