### ISSUE TITLE
How to uninstall

### ISSUE THREAD

**Issue by meminens** [catppuccin/gnome-terminal#14]
How can I completely remove this? I accidentally installed it on my server instead of my local machine. I would like to remove the installation from the server. Thanks.

**Comment by sgoudham** [comment]
Hey :wave: 

We've now merged an `uninstall.py` script that should allow you to uninstall it on your server. Check the [README](https://github.com/catppuccin/gnome-terminal/tree/main?tab=readme-ov-file#uninstall) to see how to do it.

Thanks!
