### ISSUE TITLE
Error fetching the palette: <urlopen error unknow url type: https>

### ISSUE THREAD

**Issue by filipelperes** [catppuccin/gnome-terminal#16]
Why when I run install.py return: 

"Error fetching the palette: < urlopen error unknow url type: https >"

**Comment by backwardspy** [comment]
hi! you need a python interpreter that was compiled with https support; the script cannot work without it. any recent official python build should have this by default, please check what you can do for your OS/architecture. if you need help with this, let me know as much as possible about your system and i'll see what i can do to assist.

**Comment by sgoudham** [comment]
Closing this issue as the author hasn't responded back to this issue. 
Feel free to re-open if you're still running into this and we can try to help!
