### ISSUE TITLE
Make colour scheme only

### ISSUE THREAD

**Issue by ghost** [catppuccin/gnome-terminal#17]
The install script adds profiles to the terminal, but a profile contains a lot more settings than just the colour scheme...

I'd like to suggest allowing the option of *just* adding a colour scheme, that can be used with an existing profile.

i.e.:
![image](https://github.com/catppuccin/gnome-terminal/assets/2385329/fa9338cf-3a7c-43d3-81ff-a3c5ffe0d103)

**Comment by backwardspy** [comment]
hi, thanks for raising this! unfortunately the "built-in schemes" list in gnome terminal cannot be customised. the colour schemes there are defined in gnome terminal's source code and therefore cannot be modified without a source patch & recompilation.
