### ISSUE TITLE
Update install script to create new profile

### ISSUE THREAD

**Issue by braheezy** [catppuccin/gnome-terminal#2]
Hello I was wondering if the `install.sh` script could be updated to create new profiles for users?

For example, `./install.sh catppuccin` might overwrite the existing profile `catppuccin`, or if it doesn't exist, create it in the same way the `Default` profile is currently made.

Use case: Setting up this theme from a non-interactive session, so clicking on gnome-terminal and creating the initial profile isn't available.

**Comment by nekowinston** [comment]
Closed with https://github.com/catppuccin/gnome-terminal/commit/8400cbed98eeefc08da5dd1456107da0d49fc665
