### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by ghost** [catppuccin/gnome-terminal#22]
It exits with this:

```Brak schematu „org.gnome.Terminal.ProfilesList”
Brak schematu „org.gnome.Terminal.ProfilesList”
Setting de8a9081-8352-4ce4-9519-5de655ad9361/ visible-name to 'Catppuccin Latte'
Brak schematu „org.gnome.Terminal.Legacy.Profile”
Traceback (most recent call last):
  File "<stdin>", line 71, in <module>
  File "<stdin>", line 57, in gsettings_set
  File "/usr/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['gsettings', 'set', 'org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:de8a9081-8352-4ce4-9519-5de655ad9361/', 'visible-name', "'Catppuccin Latte'"]' returned non-zero exit status 1.
```

I tried running locally to no avail.

**Comment by ghost** [comment]
nevermind i see what i did wrong

**Comment by duganchen** [comment]
@Chorwacjen And what did you do wrong? I'm seeing the exact same thing on Fedora 41.

Googling it just got me this:

https://www.reddit.com/r/archlinux/comments/1era7lj/cannot_install_gnome_terminal_theme/

**Comment by Beacon6** [comment]
Hey @duganchen I'm the maintainer of this port. Please try running:
```
gsettings get org.gnome.Terminal.ProfilesList list
```
and paste the results.

Once we diagnose the issue I will improve the error handling of the script. @Chorwacjen I would also greatly appreciate the info about what fixed it for you.

**Comment by ghost** [comment]
no dont open this it just turns out the new gnome terminal is not the same as the old one and they are not compatible, and I did not know nor noticed that.

**Comment by duganchen** [comment]
❯ gsettings get org.gnome.Terminal.ProfilesList list
    No such schema “org.gnome.Terminal.ProfilesList”

@Chorwacjen Obviously, the scope of this ticket should include getting this theme working with the current gnome-terminal releases. Which means it should currently be open. If you will continue to be difficult about this, then I will enter a new ticket that you cannot close.

**Comment by ghost** [comment]
This is GNOME Console now, though, not terminal. They are absolutely different applications at this point, considering that their support and functions are a tad bit different now and many other things are different.

**Comment by duganchen** [comment]
Looks like it's actually Ptyxis, but Fedora just identifies it as "Terminal".

@Beacon6 As Fedora 41 outright changed the terminal to Ptyxis, how do you want to handle this?

**Comment by sgoudham** [comment]
If custom colour schemes are possible in Ptyxis and can be set via the command line or imported via a file, then we would want a separate `catppuccin/ptyxis` repository instead of adding support via `catppuccin/gnome-terminal`.

^ This would be dependant on what the difference is in applying themes to Ptyxis. If it's as simple as changing the schema path then we could add support for it here and redirect to this repository but this would require someone else other than me to investigate and report back.

**Comment by duganchen** [comment]
Alright, looks like I owe @Chorwacjen an apology.

Anyway, it looks like Ptyxis actually ships with Catppuccin.

https://gitlab.gnome.org/chergert/ptyxis/-/tree/main/src/palettes

**Comment by Beacon6** [comment]
@duganchen @Chorwacjen That's great, thanks for the info, it will be useful going forward. Yeah, as @sgoudham said, if it's a different emulator then it would require a new port, but I can see the colorscheme is already provided :)

**Comment by sgoudham** [comment]
We recently updated our ANSI colours and are still in the process of rolling them out so I think would be good regardless for Catppuccin to have a `catppuccin/ptyxis` repository.

@Chorwacjen - It would be good going forward to provide more information on issues before closing them to be kinder to people, and yourself for that matter, in the future.

@duganchen - While I agree that @Chorwacjen should have provided more information, I do not think they were being, as you put it, "difficult" and would encourage you to assume good intentions first as noted in our [CoC](https://github.com/catppuccin/.github/blob/main/CODE_OF_CONDUCT.md).

In any case, I'll be locking this conversation as there is no more context to add for the original issue raised. Thanks all.
