### ISSUE TITLE
Trying to install get error

### ISSUE THREAD

**Issue by Salvodif** [catppuccin/gnome-terminal#26]
I don't know why this happened

> └─(16:47:01)──> curl -L https://raw.githubusercontent.com/catppuccin/gnome-terminal/v1.0.0/install.py | python3 -                                       1 ↵ ──(Tue,Dec24)─┘
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100  4057  100  4057    0     0  80567      0 --:--:-- --:--:-- --:--:-- 81140
> No such schema “org.gnome.Terminal.ProfilesList”
> Setting de8a9081-8352-4ce4-9519-5de655ad9361/ visible-name to 'Catppuccin Latte'
> No such schema “org.gnome.Terminal.Legacy.Profile”
> Traceback (most recent call last):
>   File "<stdin>", line 102, in <module>
>   File "<stdin>", line 64, in gsettings_set
>   File "/usr/lib64/python3.13/subprocess.py", line 472, in check_output
>     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
>            ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>                **kwargs).stdout
>                ^^^^^^^^^
>   File "/usr/lib64/python3.13/subprocess.py", line 577, in run
>     raise CalledProcessError(retcode, process.args,
>                              output=stdout, stderr=stderr)
> subprocess.CalledProcessError: Command '['gsettings', 'set', 'org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:de8a9081-8352-4ce4-9519-5de655ad9361/', 'visible-name', "'Catppuccin Latte'"]' returned non-zero exit status 1.
> 

This is my setup

> OS: Fedora Linux 41 (Workstation Edition) x86_64
> Kernel: Linux 6.12.5-200.fc41.x86_64
> Shell: zsh 5.9
> DE: GNOME 47.2
> WM: Mutter (Wayland)
> WM Theme: Qogir-Manjaro-Dark
> Theme: Qogir-Manjaro-Dark [GTK2/3/4]
> Icons: Qogir-Manjaro-Dark [GTK2/3/4]
> 
> Terminal 47.6

**Comment by Beacon6** [comment]
Hey, this is a known issue with Fedora which changed its default terminal emulator to 'Ptyxis' and kept the 'Terminal' name which leads to a lot of confusion with users. Other users have reported that Ptyxis has a built in Catppuccin theme, is that not the case for you?

EDIT: here is a [link](https://github.com/catppuccin/gnome-terminal/issues/22) to a similar issue

**Comment by Salvodif** [comment]
> Hey, this is a known issue with Fedora which changed its default terminal emulator to 'Ptyxis' and kept the 'Terminal' name which leads to a lot of confusion with users. Other users have reported that Ptyxis has a built in Catppuccin theme, is that not the case for you?
> 
> EDIT: here is a [link](https://github.com/catppuccin/gnome-terminal/issues/22) to a similar issue

I'll check
merry Christmas

**Comment by Beacon6** [comment]
Let me know if you get the issue resolved!

Merry Christmas!

**Comment by Salvodif** [comment]
> Let me know if you get the issue resolved!
> 
> Merry Christmas!

it's not a very solution, it seems

**Comment by Beacon6** [comment]
> > Let me know if you get the issue resolved!
> 
> > 
> 
> > Merry Christmas!
> 
> 
> 
> it's not a very solution, it seems

Yes, we can't fix that issue without creating a separate port for that specific application, which is beyond my control. I thought you might be able to find the built-in profile for Ptyxis. This repository is for the Gnome Terminal port which is a completely different application than the one Fedora uses currently.

**Comment by Mr-MooMoo** [comment]
For Fedora users (Ptyxis) : Under Appearance -> Show All Palettes, there are all Catppuccin themes built in, as state above.
