### ISSUE TITLE
VIM command/info text is to bright

### ISSUE THREAD

**Issue by lxwulf** [catppuccin/gnome-terminal#7]
The VIM commands, but especially the info texts from vim are a little too bright or did I, something wrong? I have no color set on VIM or the GNOME Terminal, except yours, of course. It is the Mocha theme, but the problem resides also on the other themes.

![image](https://github.com/catppuccin/gnome-terminal/assets/44492381/fcf6030f-ed42-45ef-990e-ef6787d3b1e7)

Edit: wrote the text miss typed and send without text :sweat_smile:

**Comment by nekowinston** [comment]
Can you try with `TERM=xterm-256color` set?

**Comment by lxwulf** [comment]
Yes, much better together that I changed my font from “ultra light” to “extra light”. But it's not that clean readable like in other editors like vscode or pycharm. 

Do I need to add this variable to my `bashrc` file?

Do you have else any tips which I maybe missed? I really like your theme, especially I can use this on different software – really nice!

**Comment by lxwulf** [comment]
Sorry I'm late to this, I need to update you. Sadly, this didn't help me. I found out that I selected another color palette. I reinstalled your profiles and tried out to set the new environment variable `TERM=xterm-256color` but it didn't help…

It got even worse now because there is no color highlighting anymore…

When you need more information just ask, I would try to deliver them.

**Comment by lxwulf** [comment]
Just a comment for the notification.
