### ISSUE TITLE
installer not working

### ISSUE THREAD

**Issue by popcornman209** [catppuccin/gnome-terminal#8]
not sure why, but whenever i use the curl, or i manually download it and run the install.py file, its just stuck. the terminal does not display anything, or do anything.
![image](https://github.com/catppuccin/gnome-terminal/assets/135404395/0e303667-14c2-4842-b623-6e8a258e13d6)

**Comment by nekowinston** [comment]
Can you try to download [`installer.py`](https://raw.githubusercontent.com/catppuccin/gnome-terminal/main/install.py) and run the downloaded file? `python3 ./installer.py`

**Comment by bagelwaffle** [comment]
The command works fine for me, do you have python3 installed?

**Comment by popcornman209** [comment]
i have python3
![image](https://github.com/catppuccin/gnome-terminal/assets/135404395/2d5796ca-54ac-428e-94f3-d594724af399)
and when i download install.py and run it its still blank
![image](https://github.com/catppuccin/gnome-terminal/assets/135404395/24bd8e2f-af14-406a-ad1b-fecdc62aaa33)

**Comment by popcornman209** [comment]
> The command works fine for me, do you have python3 installed?
yes i have python 3.10.6
![image](https://github.com/catppuccin/gnome-terminal/assets/135404395/f47a5913-2d2f-4bf4-908d-aa679f6314f3)

**Comment by popcornman209** [comment]
> Can you try to download [`installer.py`](https://raw.githubusercontent.com/catppuccin/gnome-terminal/main/install.py) and run the downloaded file? `python3 ./installer.py`
still blank
![image](https://github.com/catppuccin/gnome-terminal/assets/135404395/25c6593c-9de4-4129-a73b-5e6f1e3ea597)

**Comment by popcornman209** [comment]
after running it through a script i made that finds where it gets stuck, its getting stuck on line 18
'res = urlopen(f"{palette_repo}/{commit_sha}/palette.json").read().decode("utf-8")'

**Comment by popcornman209** [comment]
i fixed the problem, was a bit of a hack but it worked.
i used a script i made to see what line it was getting stuck on, it was line 18:
`res = urlopen(f"{palette_repo}/{commit_sha}/palette.json").read().decode("utf-8")`
so i just went to the link manually and downloaded the json file and changed line 18 to be:
`res = open("pallet.json","r").read()`
which fixed it! i have no clue why it was not working for me, but it did fix it.

**Comment by nekowinston** [comment]
Interesting, but I can't reproduce this on my machine. FYI, #6 added a `--local` option, so you could also use `python3 install.py --local ./palette.json` if the network request fails for whatever reason.
