### ISSUE TITLE
`File on disk has changed` message is barely readable

### ISSUE THREAD

**Issue by SkullHex2** [catppuccin/gnome-terminal#9]
<p align="center">

  <img src="https://github.com/catppuccin/gnome-terminal/assets/131589499/73ae7b99-0fb6-4254-ab92-8fe1956b8199" />

</p>

**Comment by sgoudham** [comment]
Hey :wave:,
Sorry for how long it's taken for a response on this issue. 

We've just updated the ANSI colours which _should_ improve the readability of that prompt by a _little_. It is highly unlikely we'll be making future updates/improvements to our ANSI colours so I'm going to close this issue as resolved.

I'd encourage you to read https://github.com/catppuccin/catppuccin/issues/1961 for further context on the above decision, thanks!
